### ISSUE TITLE
missing install instructions

### ISSUE THREAD

**Issue by bcatalfo** [Georg2002/SimpleEPUBReader#1]
how do i install (arch)

**Comment by Georg2002** [comment]
I have now added a release
This application is portable, so it will run just fine from any folder.

As for arch:
While this was made for windows, I don't see any reason why it shouldn't work with wine or whatever.
Can't help you with that, but should get it to run and get an error I'll fix it

**Comment by KonstantinDjairo** [comment]
it's really a good reader for japanese novels, im a linux user but i think we can run it with wine
